[package]
name = "sx1268-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
defmt = "1.0.1"
embedded-hal = { version = "1.0.0", features = ["defmt-03"] }

[dev-dependencies]
embedded-hal-mock = "0.11.1"
